version: '3'

services: 
  data:
    build: .
    entrypoint: bash
    volumes:
      - .:/srv/wikimetrics:z
      - ./wikimetrics/config/docker_config:/srv/wikimetrics/config:z

  web:
    build: .
    entrypoint:
      - uwsgi
      - --master
      - --http
      - :5000
      - --py-autoreload
      - "10"
      - --wsgi-file
      - wikimetrics/api.wsgi
    volumes:
      - .:/srv/wikimetrics:z
      - ./wikimetrics/config/docker_config:/srv/wikimetrics/config:z
    ports:
      - "5000:5000"
    links:
      - redis
      - db
      - create_db
      - upgrade_db

  redis:
    image: redis

  db:
    image: mysql:5.5
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=wikimetrics
      - MYSQL_PASSWORD=wikimetrics
    volumes:
      - .:/srv/wikimetrics:z
      - ./wikimetrics/config/docker_config:/srv/wikimetrics/config:z
    expose:
       - "3306"

  create_db:
    build: .
    entrypoint:
      - python
      - dev_createdb.py
    volumes:
      - .:/srv/wikimetrics:z
      - ./wikimetrics/config/docker_config:/srv/wikimetrics/config:z
    links:
      - db

  upgrade_db:
    build: .
    entrypoint:
      - alembic
      - upgrade
      - head
    volumes:
      - .:/srv/wikimetrics:z
      - ./wikimetrics/config/docker_config:/srv/wikimetrics/config:z
    links:
      - db
      - create_db

  queue:
    build: .
    user: www-data
    entrypoint:
      - wikimetrics
      - --mode
      - queue
      - --db-config
      - ./wikimetrics/config/db_config.yaml
      - --web-config
      - ./wikimetrics/config/web_config.yaml
      - --queue-config
      - ./wikimetrics/config/queue_config.yaml
    volumes:
      - .:/srv/wikimetrics:z
    links:
      - redis
      - db

  scheduler:
    build: .
    entrypoint:
      - wikimetrics
      - --mode
      - scheduler
      - --db-config
      - ./wikimetrics/config/db_config.yaml
      - --web-config
      - ./wikimetrics/config/web_config.yaml
      - --queue-config
      - ./wikimetrics/config/queue_config.yaml
    volumes:
      - .:/srv/wikimetrics:z
    links:
      - redis
      - db

  test:
    build: .
    environment:
      - C_FORCE_ROOT="true"
    entrypoint:
      - bash
    volumes:
      - .:/srv/wikimetrics:z
      - ./wikimetrics/config/docker_config:/srv/wikimetrics/config:z
    links:
      - redis
      - db
      - create_db
      - upgrade_db
