"""
Allow recurrent reports

Revision ID: 1a5740750a28
Revises: 1fb575f848af
Create Date: 2014-02-24 15:21:32.499948

"""

# revision identifiers, used by Alembic.
revision = '1a5740750a28'
down_revision = '1fb575f848af'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('recurrent', sa.Boolean(), nullable=False))
    op.add_column('report', sa.Column('recurrent_parent_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(
        'uix_report',
        'report',
        ['recurrent_parent_id', 'created']
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uix_report', 'report')
    op.drop_column('report', 'recurrent_parent_id')
    op.drop_column('report', 'recurrent')
    ### end Alembic commands ###
