"""empty message

Revision ID: 483df9b9a389
Revises: 1ba1b62367d4
Create Date: 2014-10-17 00:15:40.976133

"""

# revision identifiers, used by Alembic.
revision = '483df9b9a389'
down_revision = '1ba1b62367d4'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_wiki_user_project', table_name='wiki_user')
    ### end Alembic commands ###


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_wiki_user_project', 'wiki_user',
                    ['project', 'mediawiki_userid', 'validating_cohort'], unique=True)
    ### end Alembic commands ###
