"""Initial Revision

Revision ID: 492fe78451c6
Revises: None
Create Date: 2014-02-04 13:11:45.727956

"""

# revision identifiers, used by Alembic.
revision = '492fe78451c6'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(length=50), nullable=True),
        sa.Column('email', sa.String(length=254), nullable=True),
        sa.Column('role', sa.String(length=50), nullable=True),
        sa.Column('google_id', sa.String(length=254), nullable=True),
        sa.Column('meta_mw_id', sa.String(length=254), nullable=True),
        sa.Column('authenticated', sa.Boolean(), nullable=True),
        sa.Column('active', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'report',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created', sa.DateTime(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('queue_result_key', sa.String(length=50), nullable=True),
        sa.Column('result_key', sa.String(length=50), nullable=True),
        sa.Column('status', sa.String(length=50), nullable=True),
        sa.Column('name', sa.String(length=2000), nullable=True),
        sa.Column('show_in_ui', sa.Boolean(), nullable=True),
        sa.Column('parameters', sa.String(length=4000), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'wiki_user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('mediawiki_username', sa.String(length=255), nullable=True),
        sa.Column('mediawiki_userid', sa.Integer(), nullable=True),
        sa.Column('project', sa.String(length=45), nullable=True),
        sa.Column('valid', sa.Boolean(), nullable=True),
        sa.Column('reason_invalid', sa.String(length=200), nullable=True),
        sa.Column('validating_cohort', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'cohort',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=50), nullable=True),
        sa.Column('description', sa.String(length=254), nullable=True),
        sa.Column('default_project', sa.String(length=50), nullable=True),
        sa.Column('created', sa.DateTime(), nullable=True),
        sa.Column('changed', sa.DateTime(), nullable=True),
        sa.Column('enabled', sa.Boolean(), nullable=True),
        sa.Column('public', sa.Boolean(), nullable=True),
        sa.Column('validated', sa.Boolean(), nullable=True),
        sa.Column('validate_as_user_ids', sa.Boolean(), nullable=True),
        sa.Column('validation_queue_key', sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'cohort_wiki_user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('wiki_user_id', sa.Integer(), nullable=True),
        sa.Column('cohort_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['cohort_id'], ['cohort.id'], ),
        sa.ForeignKeyConstraint(['wiki_user_id'], ['wiki_user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'cohort_user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('cohort_id', sa.Integer(), nullable=True),
        sa.Column('role', sa.String(length=45), nullable=True),
        sa.ForeignKeyConstraint(['cohort_id'], ['cohort.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cohort_user')
    op.drop_table('cohort_wiki_user')
    op.drop_table('cohort')
    op.drop_table('wiki_user')
    op.drop_table('report')
    op.drop_table('user')
    ### end Alembic commands ###
