SQL_ECHO                        : False
# For testing with mysql locally (useful for manual connection survival tests)
WIKIMETRICS_ENGINE_URL          : 'mysql://wikimetrics:wikimetrics@db/wikimetrics'
WIKIMETRICS_POOL_SIZE           : 20
MEDIAWIKI_ENGINE_URL_TEMPLATE   : 'mysql://wikimetrics:wikimetrics@db/{0}'
MEDIAWIKI_POOL_SIZE             : 32
MEDIAWIKI_PROJECT_LIST          : 'https://noc.wikimedia.org/conf/dblists/all.dblist'
CENTRALAUTH_ENGINE_URL          : 'mysql://wikimetrics:wikimetrics@db/centralauth'
DEBUG                           : True
REVISION_TABLENAME              : 'revision_userindex'
ARCHIVE_TABLENAME               : 'archive_userindex'
REPLICATION_LAG_MW_PROJECTS     : [] # empty, so inactive test wikis don't block us
REPLICATION_LAG_THRESHOLD       : 3 # (measured in hours)
