#!/bin/bash

# installs dependencies

# Need newer pip than comes with debian/ubuntu
sudo pip install --upgrade pip

# find newly installed pip
pip=$(which pip)

$pip install --upgrade --no-use-wheel setuptools

# is it wikimetrics_dir=${$1:-$(pwd)}?
wikimetrics_dir=${1:-$(pwd)}

cd $wikimetrics_dir
sudo $pip install -e .
echo "*** installed dependencies"

echo "WARNING: If your pip becomes broken as a result of this script, try the following:"
echo "http://stackoverflow.com/questions/7446187/no-module-named-pkg-resources"
echo "http://stackoverflow.com/questions/6200056/pip-broke-how-to-fix-distributionnotfound-error"
